# Spring配置
spring:
  # Profile配置
  profiles:
    # 需要加载的Profile配置文件
    active: dev
  # jackson配置
  jackson:
    # 不显示为null的属性
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml

# knife4j配置
knife4j:
  # 开启增强模式
  enable: true
